### ISSUE TITLE
Thoughts on improving and enforcing coding style

### ISSUE THREAD

**Issue by AMS21** [Swartz27/xray-16#1474]
Here are some general ideas to improve coding style.

Implementing these would generally be split into 2 steps.
1. Running the option on the entire code base.
2. Creating a GitHub workflow which run on every commit/pull request to verify it in the future.

- [x] Replacing tabs with spaces [ref](https://stackoverflow.com/questions/11492179/tabs-vs-space-indentation) #1477 
- [x] Source files should be encoded with UTF-8 #1480 [ref](https://softwareengineering.stackexchange.com/questions/152780/should-my-source-code-be-in-utf-8)
- [x] Ensuring files don't contain windows-style line endings #1480 
Should be automatically handled by .gitattributes but can't hurt to check and enforce.
- [x] Running clang-format #1496 
- [x] Removing trailing white spaces #1477 
Not a big problem but look bad IMO [ref](https://softwareengineering.stackexchange.com/questions/121555/why-is-trailing-whitespace-a-big-deal)
- [x] Ensuring files end with a new line #1477 
Not required but is kind of the convention with C/C++.

To address one problem immediately. Mass formatting commits tend to mess up the `git blame`. But fortunately for this very problem the `--ignore-rev` option was created which allows you to ignore certain commits and even load these from a file.

And GitHub supports this commit ignoring out of the box see [this](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view).

So all of these mass formatting commits would be added to the `.git-blame-ignore-revs` file and should not show up in the git blame. For local use you might have to set it up manually like this.

```sh
git config --local blame.ignoreRevsFile ".git-blame-ignore-revs"
```

What are the community thoughts on this?

I have implemented all of these options in past so it shouldn't be a big problem.

**Comment by Xottab-DUTY** [comment]
Agree on everything, except details about clang-format'ing the code:
We had a discussion in #278 about the code style modification, and I also suggested to change code style for the entire code base to `snake_case`. The team didn't like the latter, and first kinda did end in nothing.

So, now, we have a very permitting mixed code style: since the original code already has mixed `snake_case` and `PascalCase` and Hungarian notation, we allow every developer to do the same. Generally, sticking to the code style of the part of the code, or the code style of the file you are working on. But developer is also allowed to stick to the his personal preference. It just should not like an alien to the existing X-Ray code base =)
Because of that, clang-format config should be modified to allow everything above and only enforce few things:
1. Always using spaces (except for comments, ignore tabs in C/C++ comments)
2. Opening bracket `{` should be always on a new line
3. Removing trailing whitespace (for the GitHub action case, it should allow it for existing code, but disallow it for new code)
(I will added more items to this list later as I recall them)

> Replacing tabs with spaces

This was done in 2017 with clang-format, but since then a little number of tabs could remain or even be added. It's good to check the code again.

> Source files should be encoded with UTF-8

The same. All sources were converted to UTF-8 somewhere in 2017, but it's good to check it again and even enforce that using GitHub workflow.

**Comment by Xottab-DUTY** [comment]
@OpenXRay/xray-contributors

**Comment by AMS21** [comment]
So now the hard part: clang-format

We _could_ run clang-format on the entire code base but I don't think this would be a good idea the diff is absolutely massive and a lot of the original code is actually formatted in a nice readable way just in a bit of a different style.

Instead I would suggest running the [clang-format-diff](https://github.com/llvm/llvm-project/blob/main/clang/tools/clang-format/clang-format-diff.py) tool on commits and pull requests which would __only__ check lines that were actually changed. So we would only enforce our formatting rules on new code and leave the old as is.

Now for the actually formatting rules there are some which I liked to at least discuss.

- [AlignConsecutiveAssignments](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#alignconsecutiveassignments) and [AlignConsecutiveDeclarations](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#alignconsecutivedeclarations)
These are currently set to `false` but in my opinion these make code a lot more readable. These can also be configured to work across lines and comments. There is also [AlignConsecutiveMacros](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#alignconsecutivedeclarations) but I don't see it as that important.

- [AllowShortEnumsOnASingleLine](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#alignconsecutivedeclarations)
Should in my opinion be set to `false`.

- [AllowShortLambdasOnASingleLine](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowshortlambdasonasingleline)
Because short functions are allowed on a single line I think lambdas should also be allowed.

- [AttributeMacros](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#attributemacros)
Are there any attribute like macros we use inside the code base?

- [BraceWrapping](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#bracewrapping)
We break on almost everything which is consistent but not on case labels. So we would get code like this:
```cpp
swtich (value)
{
    case A: {
        ...
        break;
    }
}
```
Is this intended?

Also `BeforeWhile` should should probably also be set to `true`.
Also theres `SplitEmptyFunction`, `SplitEmptyRecord` and `SplitEmptyNamespace` which when set to `false` allows them to be put on a single line.

- [BreakAfterAttributes](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#breakafterattributes)
I've seem code formatted like this already but can also be set to `leave` which would basically ignore this option.

- [BreakConstructorInitializers](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#breakconstructorinitializers)
There is `BreakConstructorInitializersBeforeComma` inside the `.clang-format` but this is not a real option. 

- [CompactNamespaces](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#compactnamespaces)
Looking at the code I think this should be set to `false`

- [EmptyLineAfterAccessModifier](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#emptylineafteraccessmodifier)
From what I've seen either `Nerver` or `Leave`

- [EmptyLineBeforeAccessModifier](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#emptylinebeforeaccessmodifier)
Very similar I guess either `Always` or `Leave`

- [FixNamespaceComments](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#fixnamespacecomments)
I don't have a strong opinion either way. It can be nice to see which closing brace belongs to which namespace but I don't think we use namespaces that much anyways.

- [IndentPPDirectives](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#indentppdirectives)
Can be used to easier see where which `#if`, `#else`, etc. block ends. But I don't think this is a very common style inside the code base. Should be set together with [PPIndentWidth](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#ppindentwidth) which should then probably also 4.

- [InsertBraces](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#insertbraces)
I think this should be set to `false` to align with the current code style. This allows code like this:
```cpp
if (x)
    return;
```
instead of
```cpp
if (x)
{
    return;
}
```
and also consider setting [RemoveBracesLLVM](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#removebracesllvm) which would not allow the second example.

- [InsertNewlineAtEOF](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#insertnewlineateof)
Since we already enforce that it only makes sense to enable this in `.clang-format` as well.

- [QualifierAlignment](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#qualifieralignment)
I think most of the code uses `Left` alignment.

- [QualifierOrder](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#qualifierorder)
Could be interesting and make the make the code more consistent. But might also be a bit too pedantic saying `static const int i = 42;` is bad and must be `const static int i = 42;` for example.

- [ReferenceAlignment](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#referencealignment)
Similar to `QualifierAlignment` I think we use `Left` alignment.

- [RemoveParentheses](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#removeparentheses)
Not sure if this is actually needed or would provide more problems than it solves. Also gcc has the [-Wparentheses](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wparentheses) warning which should catch these exact cases.

- [SortIncludes](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#sortincludes)
I like to sort my includes personally since it makes reading the include list easier like seeing everything which comes from one module close together and very easily spotting duplicate includes. But I also see the point in rejecting code which has not sorted its includes as a bit pedantic and it is currently disable in the `.clang-format` file.

- [SpaceAfterLogicalNot](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spaceafterlogicalnot) [SpaceAfterTemplateKeyword](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spaceaftertemplatekeyword) [SpaceBeforeCaseColon](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spacebeforecasecolon) [SpaceBeforeSquareBrackets](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spacebeforesquarebrackets) [SpaceInEmptyBlock](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spaceinemptyblock) [SpacesInParens](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spacesinparens)
I think these should all be set to `false`.

- [SpaceAroundPointerQualifiers](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spacearoundpointerqualifiers)
I think `before` makes the most sense here.

- [SpaceBeforeCpp11BracedList](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spacebeforecpp11bracedlist)
Honestly not sure about this one.

- [SpaceBeforeCtorInitializerColon](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spacebeforectorinitializercolon)
I think this should be set to `true`.

**Comment by Xottab-DUTY** [comment]
#1496 is now merged, hurray!

We might want to ensure our code style on naming but I guess it would be problematic to find a tool, given that it's really relaxed (we allow two general naming styles along with third "stick to the file/class" style, see my comment [here](https://github.com/OpenXRay/xray-16/pull/1496/#issuecomment-2731349826)).
